Fix GHA for docker

diff --git a/.github/workflows/nextjs.yml b/.github/workflows/nextjs.yml
--- a/.github/workflows/nextjs.yml
+++ b/.github/workflows/nextjs.yml
@@ -58,7 +58,17 @@ jobs:
       - name: Test Docker Container
         run: |
           docker run --rm -d -p 3000:3000 ${{ secrets.DOCKER_USERNAME }}/whoflopped-app:latest
-          curl --fail http://localhost:3000 || exit 1
+          # Wait for the container to start
+          for i in {1..10}; do
+            if curl --fail http://localhost:3000; then
+              echo "App is up!"
+              exit 0
+            fi
+            echo "Waiting for the app to start..."
+            sleep 3
+          done
+          echo "App failed to start"
+          exit 1
 
       # Step 6: Set up kubectl to interact with Kubernetes
       - name: Set up kubectl
